# Generated by Django 5.2.16 on 2026-07-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualLearningImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_hsk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_learning_images', to='catalog.levelhsk')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visual_learning_images', to='catalog.topic')),
            ],
            options={
                'db_table': 'visual_learning_images',
                'ordering': ['order_number', 'id'],
            },
        ),
    ]
