# Generated by Django 5.2.16 on 2026-07-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplified', models.CharField(max_length=100)),
                ('traditional', models.CharField(blank=True, max_length=100, null=True)),
                ('pinyin', models.CharField(max_length=255)),
                ('meaning_vi', models.TextField()),
                ('word_type', models.CharField(max_length=50)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField(default=0)),
                ('han_viet', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level_hsk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='catalog.levelhsk')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabularies', to='catalog.topic')),
            ],
            options={
                'db_table': 'vocabularies',
                'ordering': ['order_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSavedVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vocabularies', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='vocabulary.vocabulary')),
            ],
            options={
                'db_table': 'user_saved_vocabularies',
            },
        ),
        migrations.CreateModel(
            name='VocabularyExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_chinese', models.TextField()),
                ('pinyin', models.TextField()),
                ('meaning_vi', models.TextField()),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('order_number', models.IntegerField(default=0)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vocabulary.vocabulary')),
            ],
            options={
                'db_table': 'vocabulary_examples',
                'ordering': ['order_number', 'id'],
            },
        ),
    ]
