# Generated by Django 5.2.16 on 2026-07-22 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_grammarcategory'),
        ('vocabulary', '0002_unique_saved_vocabulary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usersavedvocabulary',
            index=models.Index(fields=['user', 'created_at'], name='saved_vocab_user_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['status', 'level_hsk', 'topic', 'order_number', 'id'], name='vocab_st_lv_tp_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['status', 'level_hsk', 'order_number', 'id'], name='vocab_st_lv_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabulary',
            index=models.Index(fields=['status', 'word_type', 'order_number', 'id'], name='vocab_st_type_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyexample',
            index=models.Index(fields=['vocabulary', 'order_number', 'id'], name='vocab_ex_vocab_ord_idx'),
        ),
    ]
