# Generated by Codex on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


LOOKUPS = {
    "exercise_content_types": [
        ("VOCABULARY", "Từ vựng"),
        ("GRAMMAR", "Ngữ pháp"),
        ("MIXED", "Tổng hợp"),
        ("EXAM", "Đề thi"),
        ("VISUAL_LEARNING", "Học qua hình ảnh"),
    ],
    "exercise_modes": [
        ("PRACTICE", "Luyện tập"),
        ("TEST", "Kiểm tra"),
        ("MOCK_EXAM", "Thi thử"),
    ],
    "exercise_section_types": [
        ("LISTENING", "Nghe"),
        ("READING", "Đọc"),
        ("WRITING", "Viết"),
        ("GENERAL", "Chung"),
    ],
    "question_types": [
        ("MULTIPLE_CHOICE", "Trắc nghiệm"),
        ("TRUE_FALSE", "Đúng sai"),
        ("FILL_BLANK", "Điền chỗ trống"),
        ("REORDER_SENTENCE", "Sắp xếp câu"),
        ("WRITING_TEXT", "Viết câu"),
        ("PICTURE_SENTENCE", "Nhìn tranh đặt câu"),
        ("LISTENING_CHOICE", "Nghe chọn đáp án"),
    ],
    "answer_grading_statuses": [
        ("AUTO_GRADED", "Đã chấm tự động"),
        ("PENDING", "Chờ chấm"),
        ("GRADED", "Đã chấm"),
        ("NEEDS_REVIEW", "Cần xem lại"),
    ],
}


def table_exists(cursor, table):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_name = %s
        """,
        [table],
    )
    return cursor.fetchone()[0] > 0


def column_exists(cursor, table, column):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND table_name = %s AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone()[0] > 0


def index_exists(cursor, table, index_name):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.statistics
        WHERE table_schema = DATABASE() AND table_name = %s AND index_name = %s
        """,
        [table, index_name],
    )
    return cursor.fetchone()[0] > 0


def fk_exists(cursor, table, column):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.key_column_usage
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
          AND referenced_table_name IS NOT NULL
        """,
        [table, column],
    )
    return cursor.fetchone()[0] > 0


def fk_names(cursor, table, column):
    cursor.execute(
        """
        SELECT constraint_name
        FROM information_schema.key_column_usage
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
          AND referenced_table_name IS NOT NULL
        """,
        [table, column],
    )
    return [row[0] for row in cursor.fetchall()]


def add_column(cursor, table, column, definition):
    if not column_exists(cursor, table, column):
        cursor.execute(f"ALTER TABLE `{table}` ADD COLUMN `{column}` {definition}")


def drop_column(cursor, table, column):
    if column_exists(cursor, table, column):
        for fk_name in fk_names(cursor, table, column):
            cursor.execute(f"ALTER TABLE `{table}` DROP FOREIGN KEY `{fk_name}`")
        cursor.execute(f"ALTER TABLE `{table}` DROP COLUMN `{column}`")


def add_fk(cursor, table, column, ref_table, constraint_name):
    if fk_exists(cursor, table, column):
        return
    index_name = f"{table}_{column}_idx"
    if not index_exists(cursor, table, index_name):
        cursor.execute(f"CREATE INDEX `{index_name}` ON `{table}` (`{column}`)")
    cursor.execute(
        f"""
        ALTER TABLE `{table}`
        ADD CONSTRAINT `{constraint_name}`
        FOREIGN KEY (`{column}`) REFERENCES `{ref_table}` (`id`)
        """
    )


def create_lookup_table(cursor, table):
    cursor.execute(
        f"""
        CREATE TABLE IF NOT EXISTS `{table}` (
          `id` bigint NOT NULL AUTO_INCREMENT,
          `code` varchar(50) NOT NULL,
          `name` varchar(100) NOT NULL,
          `description` longtext NULL,
          `order_number` int NOT NULL DEFAULT 0,
          `status` tinyint(1) NOT NULL DEFAULT 1,
          PRIMARY KEY (`id`),
          UNIQUE KEY `{table}_code_uniq` (`code`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """
    )


def seed_lookup_tables(cursor):
    for table, rows in LOOKUPS.items():
        for order_number, (code, name) in enumerate(rows, start=1):
            cursor.execute(
                f"""
                INSERT INTO `{table}` (`code`, `name`, `order_number`, `status`)
                VALUES (%s, %s, %s, 1)
                ON DUPLICATE KEY UPDATE
                  `name` = VALUES(`name`),
                  `order_number` = VALUES(`order_number`),
                  `status` = VALUES(`status`)
                """,
                [code, name, order_number],
            )


def migrate_legacy_exercise_set_code(cursor, old_column, new_column, lookup_table):
    add_column(cursor, "exercise_sets", new_column, "bigint NULL")
    if column_exists(cursor, "exercise_sets", old_column):
        cursor.execute(
            f"""
            UPDATE `exercise_sets` es
            JOIN `{lookup_table}` lookup ON lookup.`code` = es.`{old_column}`
            SET es.`{new_column}` = lookup.`id`
            WHERE es.`{new_column}` IS NULL
            """
        )
        drop_column(cursor, "exercise_sets", old_column)


def create_exam_structure_tables(cursor):
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS `exercise_sections` (
          `id` bigint NOT NULL AUTO_INCREMENT,
          `title` varchar(255) NOT NULL,
          `instruction` longtext NULL,
          `audio_url` longtext NULL,
          `time_limit_minutes` int NULL,
          `max_score` decimal(6,2) NULL,
          `order_number` int NOT NULL DEFAULT 0,
          `status` tinyint(1) NOT NULL DEFAULT 1,
          `created_at` datetime(6) NOT NULL,
          `updated_at` datetime(6) NOT NULL,
          `exercise_set_id` bigint NOT NULL,
          `section_type_id` bigint NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `exercise_sections_set_order_uniq` (`exercise_set_id`, `order_number`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS `exercise_parts` (
          `id` bigint NOT NULL AUTO_INCREMENT,
          `title` varchar(255) NOT NULL,
          `instruction` longtext NULL,
          `order_number` int NOT NULL DEFAULT 0,
          `status` tinyint(1) NOT NULL DEFAULT 1,
          `created_at` datetime(6) NOT NULL,
          `updated_at` datetime(6) NOT NULL,
          `exercise_set_id` bigint NOT NULL,
          `section_id` bigint NULL,
          `question_type_id` bigint NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `exercise_parts_set_order_uniq` (`exercise_set_id`, `order_number`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """
    )
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS `question_groups` (
          `id` bigint NOT NULL AUTO_INCREMENT,
          `title` varchar(255) NULL,
          `instruction` longtext NULL,
          `passage_text` longtext NULL,
          `passage_pinyin` longtext NULL,
          `audio_url` longtext NULL,
          `image_url` longtext NULL,
          `start_time_seconds` decimal(8,2) NULL,
          `end_time_seconds` decimal(8,2) NULL,
          `order_number` int NOT NULL DEFAULT 0,
          `status` tinyint(1) NOT NULL DEFAULT 1,
          `created_at` datetime(6) NOT NULL,
          `updated_at` datetime(6) NOT NULL,
          `exercise_set_id` bigint NOT NULL,
          `section_id` bigint NULL,
          `part_id` bigint NULL,
          PRIMARY KEY (`id`),
          UNIQUE KEY `question_groups_set_order_uniq` (`exercise_set_id`, `order_number`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """
    )


def repair_exercise_schema(apps, schema_editor):
    cursor = schema_editor.connection.cursor()

    for table in LOOKUPS:
        create_lookup_table(cursor, table)
    seed_lookup_tables(cursor)

    if table_exists(cursor, "exercise_sets"):
        migrate_legacy_exercise_set_code(cursor, "content_type", "content_type_id", "exercise_content_types")
        migrate_legacy_exercise_set_code(cursor, "legacy_content_type", "content_type_id", "exercise_content_types")
        migrate_legacy_exercise_set_code(cursor, "exercise_mode", "exercise_mode_id", "exercise_modes")
        migrate_legacy_exercise_set_code(cursor, "legacy_exercise_mode", "exercise_mode_id", "exercise_modes")
        drop_column(cursor, "exercise_sets", "grammar_category_id")
        add_fk(cursor, "exercise_sets", "content_type_id", "exercise_content_types", "fk_ex_sets_content_type")
        add_fk(cursor, "exercise_sets", "exercise_mode_id", "exercise_modes", "fk_ex_sets_mode")

    create_exam_structure_tables(cursor)
    add_fk(cursor, "exercise_sections", "exercise_set_id", "exercise_sets", "fk_ex_sections_set")
    add_fk(cursor, "exercise_sections", "section_type_id", "exercise_section_types", "fk_ex_sections_type")
    add_fk(cursor, "exercise_parts", "exercise_set_id", "exercise_sets", "fk_ex_parts_set")
    add_fk(cursor, "exercise_parts", "section_id", "exercise_sections", "fk_ex_parts_section")
    add_fk(cursor, "exercise_parts", "question_type_id", "question_types", "fk_ex_parts_qtype")
    add_fk(cursor, "question_groups", "exercise_set_id", "exercise_sets", "fk_q_groups_set")
    add_fk(cursor, "question_groups", "section_id", "exercise_sections", "fk_q_groups_section")
    add_fk(cursor, "question_groups", "part_id", "exercise_parts", "fk_q_groups_part")

    if table_exists(cursor, "questions"):
        add_column(cursor, "questions", "section_id", "bigint NULL")
        add_column(cursor, "questions", "part_id", "bigint NULL")
        add_column(cursor, "questions", "question_group_id", "bigint NULL")
        add_column(cursor, "questions", "question_type_id", "bigint NULL")
        add_column(cursor, "questions", "correct_answer_text", "longtext NULL")
        add_column(cursor, "questions", "start_time_seconds", "decimal(8,2) NULL")
        add_column(cursor, "questions", "end_time_seconds", "decimal(8,2) NULL")
        add_fk(cursor, "questions", "section_id", "exercise_sections", "fk_questions_section")
        add_fk(cursor, "questions", "part_id", "exercise_parts", "fk_questions_part")
        add_fk(cursor, "questions", "question_group_id", "question_groups", "fk_questions_group")
        add_fk(cursor, "questions", "question_type_id", "question_types", "fk_questions_qtype")

    if table_exists(cursor, "attempt_answers"):
        add_column(cursor, "attempt_answers", "answer_text", "longtext NULL")
        add_column(cursor, "attempt_answers", "answer_payload", "json NULL")
        add_column(cursor, "attempt_answers", "grading_status_id", "bigint NULL")
        for fk_name in fk_names(cursor, "attempt_answers", "selected_option_id"):
            cursor.execute(f"ALTER TABLE `attempt_answers` DROP FOREIGN KEY `{fk_name}`")
        cursor.execute("ALTER TABLE `attempt_answers` MODIFY `selected_option_id` bigint NULL")
        add_fk(cursor, "attempt_answers", "selected_option_id", "question_options", "fk_attempt_answers_option")
        add_fk(cursor, "attempt_answers", "grading_status_id", "answer_grading_statuses", "fk_attempt_answers_grading")


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(repair_exercise_schema, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="AnswerGradingStatus",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(max_length=50, unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                    ],
                    options={"db_table": "answer_grading_statuses", "ordering": ["order_number", "code"]},
                ),
                migrations.CreateModel(
                    name="ExerciseContentType",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(max_length=50, unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                    ],
                    options={"db_table": "exercise_content_types", "ordering": ["order_number", "code"]},
                ),
                migrations.CreateModel(
                    name="ExerciseMode",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(max_length=50, unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                    ],
                    options={"db_table": "exercise_modes", "ordering": ["order_number", "code"]},
                ),
                migrations.CreateModel(
                    name="ExerciseSectionType",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(max_length=50, unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                    ],
                    options={"db_table": "exercise_section_types", "ordering": ["order_number", "code"]},
                ),
                migrations.CreateModel(
                    name="QuestionType",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("code", models.CharField(max_length=50, unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("description", models.TextField(blank=True, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                    ],
                    options={"db_table": "question_types", "ordering": ["order_number", "code"]},
                ),
                migrations.RenameField("exerciseset", "content_type", "legacy_content_type"),
                migrations.RenameField("exerciseset", "exercise_mode", "legacy_exercise_mode"),
                migrations.RemoveField("exerciseset", "grammar_category"),
                migrations.AddField(
                    "exerciseset",
                    "content_type",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="exercise_sets", to="exercises.exercisecontenttype"),
                ),
                migrations.AddField(
                    "exerciseset",
                    "exercise_mode",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="exercise_sets", to="exercises.exercisemode"),
                ),
                migrations.RemoveField("exerciseset", "legacy_content_type"),
                migrations.RemoveField("exerciseset", "legacy_exercise_mode"),
                migrations.AddField("attemptanswer", "answer_payload", models.JSONField(blank=True, null=True)),
                migrations.AddField("attemptanswer", "answer_text", models.TextField(blank=True, null=True)),
                migrations.AddField(
                    "attemptanswer",
                    "grading_status",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="attempt_answers", to="exercises.answergradingstatus"),
                ),
                migrations.AlterField(
                    "attemptanswer",
                    "selected_option",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="exercises.questionoption"),
                ),
                migrations.AddField("question", "correct_answer_text", models.TextField(blank=True, null=True)),
                migrations.AddField("question", "end_time_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                migrations.AddField("question", "start_time_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                migrations.CreateModel(
                    name="ExerciseSection",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(max_length=255)),
                        ("instruction", models.TextField(blank=True, null=True)),
                        ("audio_url", models.TextField(blank=True, null=True)),
                        ("time_limit_minutes", models.IntegerField(blank=True, null=True)),
                        ("max_score", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("exercise_set", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="exercises.exerciseset")),
                        ("section_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sections", to="exercises.exercisesectiontype")),
                    ],
                    options={"db_table": "exercise_sections", "ordering": ["order_number", "id"], "unique_together": {("exercise_set", "order_number")}},
                ),
                migrations.CreateModel(
                    name="ExercisePart",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(max_length=255)),
                        ("instruction", models.TextField(blank=True, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("exercise_set", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="parts", to="exercises.exerciseset")),
                        ("question_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="parts", to="exercises.questiontype")),
                        ("section", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="parts", to="exercises.exercisesection")),
                    ],
                    options={"db_table": "exercise_parts", "ordering": ["order_number", "id"], "unique_together": {("exercise_set", "order_number")}},
                ),
                migrations.CreateModel(
                    name="QuestionGroup",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("title", models.CharField(blank=True, max_length=255, null=True)),
                        ("instruction", models.TextField(blank=True, null=True)),
                        ("passage_text", models.TextField(blank=True, null=True)),
                        ("passage_pinyin", models.TextField(blank=True, null=True)),
                        ("audio_url", models.TextField(blank=True, null=True)),
                        ("image_url", models.TextField(blank=True, null=True)),
                        ("start_time_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ("end_time_seconds", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                        ("order_number", models.IntegerField(default=0)),
                        ("status", models.BooleanField(default=True)),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("exercise_set", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="question_groups", to="exercises.exerciseset")),
                        ("part", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="question_groups", to="exercises.exercisepart")),
                        ("section", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="question_groups", to="exercises.exercisesection")),
                    ],
                    options={"db_table": "question_groups", "ordering": ["order_number", "id"], "unique_together": {("exercise_set", "order_number")}},
                ),
                migrations.AddField("question", "part", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="exercises.exercisepart")),
                migrations.AddField("question", "question_group", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="exercises.questiongroup")),
                migrations.AddField("question", "question_type", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="questions", to="exercises.questiontype")),
                migrations.AddField("question", "section", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="questions", to="exercises.exercisesection")),
            ],
        )
    ]
