# Generated by Django 5.2.16 on 2026-07-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exam_structure_and_lookup_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongroup',
            name='part',
        ),
        migrations.RemoveField(
            model_name='question',
            name='part',
        ),
        migrations.DeleteModel(
            name='ExercisePart',
        ),
    ]
