# Generated by Django 5.2.16 on 2026-07-20 12:28

from django.db import migrations


def table_exists(cursor, table_name):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.tables
        WHERE table_schema = DATABASE() AND table_name = %s
        """,
        [table_name],
    )
    return cursor.fetchone()[0] > 0


def column_exists(cursor, table_name, column_name):
    cursor.execute(
        """
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE() AND table_name = %s AND column_name = %s
        """,
        [table_name, column_name],
    )
    return cursor.fetchone()[0] > 0


def drop_grading_status_if_exists(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        if table_exists(cursor, "attempt_answers") and column_exists(cursor, "attempt_answers", "grading_status_id"):
            cursor.execute("ALTER TABLE attempt_answers DROP COLUMN grading_status_id")
        if table_exists(cursor, "answer_grading_statuses"):
            cursor.execute("DROP TABLE answer_grading_statuses")


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_questiongroup_part_remove_question_part_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_grading_status_if_exists, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='attemptanswer',
                    name='grading_status',
                ),
                migrations.DeleteModel(
                    name='AnswerGradingStatus',
                ),
            ],
        ),
    ]
