# Generated by Django 5.2.16 on 2026-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grammar_categories',
                'ordering': ['order_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LevelHsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'level_hsks',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('order_number', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['order_number', 'name'],
            },
        ),
    ]
